# Generated by Django 5.1.3 on 2024-12-25 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_medication_date_added'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DispensedMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('date_dispensed', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.patient')),
            ],
        ),
    ]
