# Generated by Django 5.1.3 on 2024-12-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_medication_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
