# Generated by Django 5.1.3 on 2024-12-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_patient_company_name_alter_patient_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='company_name',
        ),
        migrations.AddField(
            model_name='medication',
            name='company_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
