# Generated by Django 5.1.3 on 2024-12-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_prescription_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='date',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='follow_up_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medications',
            field=models.JSONField(),
        ),
    ]
