# Generated by Django 5.1.3 on 2024-12-30 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_remove_prescription_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
