# Generated by Django 5.1.3 on 2025-01-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_medication_mr_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensedmedication',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dispensedmedication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dispensedmedication',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
