# Generated by Django 5.1.3 on 2025-01-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_billing_description_alter_billing_date_billed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispensingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_details', models.TextField(blank=True, null=True)),
                ('procedure', models.CharField(blank=True, max_length=255, null=True)),
                ('procedure_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('consultation_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_dispensed', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.patient')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
    ]
