# Generated by Django 5.1.3 on 2025-01-07 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_dispensinghistory_delete_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensedmedication',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
