# Generated by Django 5.1.3 on 2025-01-07 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_alter_medication_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='inventory.patient'),
        ),
        migrations.AlterField(
            model_name='dispensedmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_medications', to='inventory.medication'),
        ),
        migrations.AlterField(
            model_name='dispensedmedication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_medications', to='inventory.patient'),
        ),
        migrations.AlterField(
            model_name='dispensinghistory',
            name='medication_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dispensinghistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_histories', to='inventory.patient'),
        ),
        migrations.AlterField(
            model_name='dispensinghistory',
            name='procedure',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
