# Generated by Django 5.1.3 on 2025-01-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_billing_patient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensedmedication',
            name='consultation_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dispensedmedication',
            name='procedure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dispensedmedication',
            name='procedure_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
