# Generated by Django 5.1.3 on 2025-01-08 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_remove_dispensedmedication_consultation_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensedmedication',
            name='procedure',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
