# Generated by Django 5.1.3 on 2025-01-08 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_dispensedmedication_procedure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensedmedication',
            name='dispensing_history',
        ),
        migrations.DeleteModel(
            name='DispensingHistory',
        ),
    ]
