# Generated by Django 5.1.3 on 2025-01-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_remove_dispensedmedication_dispensing_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispensedmedication',
            name='procedure',
        ),
        migrations.CreateModel(
            name='DispensedMedicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('procedure', models.CharField(blank=True, max_length=255, null=True)),
                ('procedureCost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_dispensed', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.medication')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.patient')),
            ],
        ),
    ]
