# Generated by Django 5.1.3 on 2025-01-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_remove_dispensedmedicationhistory_medication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensedmedicationhistory',
            name='medication_details',
            field=models.JSONField(default=dict),
        ),
    ]
