# Generated by Django 5.1.3 on 2025-01-09 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_alter_dispensedmedicationhistory_medication_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensedmedicationhistory',
            old_name='cost',
            new_name='total_cost',
        ),
        migrations.AlterField(
            model_name='dispensedmedication',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dispensedmedication',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_medications', to='inventory.medication'),
        ),
        migrations.AlterField(
            model_name='dispensedmedication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_medications', to='inventory.patient'),
        ),
    ]
