# Generated by Django 5.1.3 on 2025-01-09 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_rename_cost_dispensedmedicationhistory_total_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensedmedicationhistory',
            old_name='total_cost',
            new_name='cost',
        ),
    ]
