# Generated by Django 5.1.3 on 2025-01-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_rename_total_cost_dispensedmedicationhistory_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispensedmedicationhistory',
            name='medication_details',
            field=models.JSONField(default=list),
        ),
    ]
