# Generated by Django 4.2.18 on 2025-02-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0034_alter_dispensedmedicationhistory_medication_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispensedmedicationhistory',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('UPI', 'UPI')], default='Cash', max_length=10),
        ),
    ]
