# Generated by Django 4.2.18 on 2025-02-07 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_dispensedmedicationhistory_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispensedmedicationhistory',
            old_name='cost',
            new_name='total_cost',
        ),
    ]
