# Generated by Django 4.2.18 on 2025-02-21 12:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0038_remove_dispensedmedicationhistory_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
