# Generated by Django 4.2.18 on 2025-02-21 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0040_medication_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='expiry_date',
        ),
    ]
