# Generated by Django 4.2.18 on 2025-02-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0041_remove_medication_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
